/* This header is autogenerated */
#ifndef GENERATED_VORTEX2D_GENERATED_SPIRV_H
#define GENERATED_VORTEX2D_GENERATED_SPIRV_H

#include <cstdint>

namespace Vortex2D
{
namespace Renderer
{
class SpirvBinary;
}

namespace SPIRV
{
extern Vortex2D::Renderer::SpirvBinary Advect_comp;
extern Vortex2D::Renderer::SpirvBinary AdvectParticles_comp;
extern Vortex2D::Renderer::SpirvBinary AdvectVelocity_comp;
extern Vortex2D::Renderer::SpirvBinary BuildDiv_comp;
extern Vortex2D::Renderer::SpirvBinary BuildMatrix_comp;
extern Vortex2D::Renderer::SpirvBinary BuildRigidbodyDiv_comp;
extern Vortex2D::Renderer::SpirvBinary CircleDist_frag;
extern Vortex2D::Renderer::SpirvBinary ConstrainRigidbodyVelocity_comp;
extern Vortex2D::Renderer::SpirvBinary ConstrainVelocity_comp;
extern Vortex2D::Renderer::SpirvBinary DampedJacobi_comp;
extern Vortex2D::Renderer::SpirvBinary DebugDataCopy_comp;
extern Vortex2D::Renderer::SpirvBinary Diagonal_comp;
extern Vortex2D::Renderer::SpirvBinary DistanceField_frag;
extern Vortex2D::Renderer::SpirvBinary Divide_comp;
extern Vortex2D::Renderer::SpirvBinary Ellipse_frag;
extern Vortex2D::Renderer::SpirvBinary Ellipse_vert;
extern Vortex2D::Renderer::SpirvBinary Extrapolate_comp;
extern Vortex2D::Renderer::SpirvBinary ExtrapolateVelocity_comp;
extern Vortex2D::Renderer::SpirvBinary GaussSeidel_comp;
extern Vortex2D::Renderer::SpirvBinary IncompletePoisson_comp;
extern Vortex2D::Renderer::SpirvBinary IntPosition_frag;
extern Vortex2D::Renderer::SpirvBinary LocalGaussSeidel_comp;
extern Vortex2D::Renderer::SpirvBinary Max_comp;
extern Vortex2D::Renderer::SpirvBinary Multiply_comp;
extern Vortex2D::Renderer::SpirvBinary MultiplyAdd_comp;
extern Vortex2D::Renderer::SpirvBinary MultiplyMatrix_comp;
extern Vortex2D::Renderer::SpirvBinary MultiplySub_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleBucket_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleClamp_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleCount_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleFromGrid_comp;
extern Vortex2D::Renderer::SpirvBinary ParticlePhi_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleSpawn_comp;
extern Vortex2D::Renderer::SpirvBinary ParticleToGrid_comp;
extern Vortex2D::Renderer::SpirvBinary PhiScale_comp;
extern Vortex2D::Renderer::SpirvBinary PolygonDist_frag;
extern Vortex2D::Renderer::SpirvBinary Position_frag;
extern Vortex2D::Renderer::SpirvBinary Position_vert;
extern Vortex2D::Renderer::SpirvBinary PreScan_comp;
extern Vortex2D::Renderer::SpirvBinary PreScanAdd_comp;
extern Vortex2D::Renderer::SpirvBinary PreScanStoreSum_comp;
extern Vortex2D::Renderer::SpirvBinary Project_comp;
extern Vortex2D::Renderer::SpirvBinary Prolongate_comp;
extern Vortex2D::Renderer::SpirvBinary Redistance_comp;
extern Vortex2D::Renderer::SpirvBinary Residual_comp;
extern Vortex2D::Renderer::SpirvBinary Restrict_comp;
extern Vortex2D::Renderer::SpirvBinary RigidbodyForce_comp;
extern Vortex2D::Renderer::SpirvBinary RigidbodyPressure_comp;
extern Vortex2D::Renderer::SpirvBinary ShrinkWrap_comp;
extern Vortex2D::Renderer::SpirvBinary Sum_comp;
extern Vortex2D::Renderer::SpirvBinary SumJ_comp;
extern Vortex2D::Renderer::SpirvBinary TexturePosition_frag;
extern Vortex2D::Renderer::SpirvBinary TexturePosition_vert;
extern Vortex2D::Renderer::SpirvBinary VelocityDifference_comp;
extern Vortex2D::Renderer::SpirvBinary VelocityMax_comp;

}
}

#endif

